=== shixianwen/report/guestbook/xml/airlines.xsd
<?xml version="1.0"?>
<xsd:schema version="1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" >
    
    <xsd:element name="airlines" type="AirlinesType" />
    <xsd:complexType name="AirlinesType">
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="airline" type="AirlineType" />
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="AirlineType">
        <xsd:sequence>
            <xsd:element name="company" >
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:maxLength  value="100"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>             
            <xsd:element name="name">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:maxLength  value="100"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>       
            <xsd:element name="price">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:maxLength  value="100"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>  

            <xsd:element name="from"  >
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:maxLength  value="100"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>     
            <xsd:element name="des" >
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:maxLength  value="100"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="flydate" >
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:maxLength  value="100"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="flytime" >
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:maxLength  value="100"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>      
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" />
    </xsd:complexType>
</xsd:schema>

=== shixianwen/report/guestbook/xml/airlines.xml
<?xml version="1.0" encoding="UTF-8"?>
<airlines xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="airlines.xsd">
    <airline id="1">
        <company>British Airways</company>
        <name>BA272</name>
        <price>255$</price>
        <from>Stockholm Arlanda Airport</from>
        <des>London Heathrow Airport</des>
        <flydate>2015/4/7</flydate>
         <flytime>17:21</flytime>
    </airline>
    <airline id="2">
        <company>British Airways</company>
        <name>BA274</name>
        <price>100$</price>
        <from>Stockholm Arlanda Airport</from>
        <des>London Heathrow Airport</des>
        <flydate>2015/4/7</flydate>
         <flytime>14:21</flytime>
    </airline>
    <airline id="3">
        <company>China Airline</company>
        <name>CA911</name>
        <price>225$</price>
        <from>Stockholm Arlanda Airport</from>
        <des>Beijing</des>
        <flydate>2015/4/6</flydate>
        <flytime>08:21</flytime>
    </airline>
</airlines>
