=== shixianwen/report/guestbook/xml/books.xsd
<?xml version="1.0"?>
<xsd:schema version="1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" >
    
    <xsd:element name="Books" type="BooksType" />
    <xsd:complexType name="BooksType">
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="Profile" type="BookType" />
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="BookType">
        <xsd:sequence>
            <xsd:element name="firstname" >
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:maxLength  value="20"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>             
            <xsd:element name="surname">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:maxLength  value="20"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>       
            <xsd:element name="password">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:maxLength  value="20"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>  

            <xsd:element name="author_id"  >
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:maxLength  value="20"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>     
            <xsd:element name="flight" >
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:maxLength  value="40"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>      
        </xsd:sequence>
        <xsd:attribute name="username" type="xsd:ID" />
    </xsd:complexType>
</xsd:schema>

=== shixianwen/report/guestbook/xml/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<Books xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="books.xsd">
    <Profile username="mike">
        <firstname>Philip</firstname>
        <surname>Opuogen</surname>
        <password>look</password>
        <author_id>mike</author_id>
        <flight>BA272</flight>
    </Profile>
    <Profile username="nickname">
        <firstname>Shixian</firstname>
        <surname>wen</surname>
        <password/>
        <author_id>nickname</author_id>
        <flight>CA911</flight>
    </Profile>
<Profile username="chengxuyuan"><firstname>gu</firstname><surname>tianyu</surname><password>asdf</password><author_id>chengxuyuan</author_id><flight>CA911</flight></Profile><Profile username="huhu123"><firstname>huan</firstname><surname>huang</surname><password>123456</password><author_id>huhu123</author_id><flight>ca911</flight></Profile><Profile username="weiliu123"><firstname>wei</firstname><surname>liu</surname><password>123456</password><author_id>weiliu123</author_id><flight>CA911</flight></Profile><Profile username="liuliuliu"><firstname>liuwei</firstname><surname>liu</surname><password>123456</password><author_id>liuliuliu</author_id><flight>CA911</flight></Profile><Profile username="xiaoqiang"><firstname>shixian</firstname><surname>wen</surname><password>123456</password><author_id>xiaoqiang</author_id><flight>CA911</flight></Profile><Profile username="SD"><firstname>weiliu</firstname><surname>234123</surname><password>1234</password><author_id>SD</author_id><flight>CA911</flight></Profile><Profile username="we"><firstname>weiliu</firstname><surname>234123</surname><password>12345</password><author_id>we</author_id><flight>CA911</flight></Profile><Profile username="sadsa"><firstname>sdas</firstname><surname>wqeqw</surname><password>wqe</password><author_id>sadsa</author_id><flight>qweq</flight></Profile><Profile username="qweq"><firstname>asdas</firstname><surname>asda</surname><password>12312</password><author_id>qweq</author_id><flight>wqeqw</flight></Profile><Profile username="xiaozhuzhu"><firstname>shixian</firstname><surname>wen</surname><password>123456</password><author_id>xiaozhuzhu</author_id><flight>ca911</flight></Profile><Profile username="wqead"><firstname>aseq</firstname><surname>32123</surname><password>qwe</password><author_id>wqead</author_id><flight>ca911</flight></Profile><Profile username="as1da"><firstname>shixian</firstname><surname>wen</surname><password>123456</password><author_id>as1da</author_id><flight>CA911</flight></Profile><Profile username="xiaoliuliu"><firstname>wei</firstname><surname>liu</surname><password>123456</password><author_id>xiaoliuliu</author_id><flight>CA911</flight></Profile><Profile username="liuliuwei"><firstname>liu</firstname><surname>wei</surname><password>123456</password><author_id>liuliuwei</author_id><flight>CA911</flight></Profile></Books>
